newarm (v1)
FRC701/Loki2016 pull request #10
Opened 2016-11-08 02:09 UTC by duane701

Replace the old (intake) arm with the new intake arm.

2016-11-15 00:19 UTC, Diego-Andrade requested changes
FTP

2016-11-15 00:19 UTC, Diego-Andrade commented on src/Commands/SetShifter.cpp
>  	// eg. Requires(chassis);
Requires is required!

2016-11-15 00:19 UTC, Diego-Andrade commented on src/Commands/ToggleArms.cpp
>  	return false;
Going to keep toggling, should be true

2016-11-15 00:19 UTC, Diego-Andrade commented on src/Commands/SetShifter.h
> +#include "Commands/Subsystem.h"
Should include command.h, not subsystem.h

2016-11-15 00:19 UTC, Diego-Andrade commented on src/Commands/SetArms.h
> +#include "Commands/Subsystem.h"
Should include command.h not subsystem.h

2016-11-15 00:19 UTC, Diego-Andrade commented on src/Commands/ToggleArms.h
>  #include "Commands/Subsystem.h"
Should include command.h not substem.h

2016-11-15 00:19 UTC, Diego-Andrade commented on src/Robot.h
>    static std::shared_ptr<Shooter> shooter;
Fix tabbing

2016-11-15 00:20 UTC, Diego-Andrade commented on src/Commands/IntakeOn.cpp
> +	mSpeed = Speed;
Use member initialization list

2016-11-16 07:19 UTC, Diego-Andrade requested changes
Spacing is still off, and some suggestions on having magic numbers

2016-11-16 07:19 UTC, Diego-Andrade commented on src/OI.cpp
>      driver.reset(new Joystick(0));
Do we want a const for driver as well? To be consistant

2016-11-16 07:19 UTC, Diego-Andrade commented on src/OI.cpp
>  	return this->driver->GetRawAxis(1);
`this->` is not necessary. Also magic number?

2016-11-16 07:19 UTC, Diego-Andrade commented on src/Robot.cpp
>  	oi.reset(new OI());
Spacing not fixed

2016-11-19 00:02 UTC, duane701 commented
Re: Spacing is still off, and some suggestions on having magic numbers

Magic numbers will be fixed in a future PR.

PTAL

2016-11-19 00:43 UTC, Diego-Andrade approved these changes

2016-11-19 00:43 UTC, Diego-Andrade commented
LGTM

2016-11-19 00:43 UTC, merged