lights subsystem (v1)
FRC701/Loki2016 pull request #15
Opened 2016-12-29 05:07 UTC by duane701

Please review these changes.

Please compile this branch to ensure that this code is correct. (I do not have a compiler.)

2017-01-02 01:51 UTC, Diego-Andrade requested changes
Code complies as is. A few inconsistencies and missing default command

2017-01-02 01:51 UTC, Diego-Andrade commented on src/RobotMap.cpp
> +    lightsShooter.reset(new Relay(1));
Could use a constant instead of fixed number for relay ports

2017-01-02 01:51 UTC, Diego-Andrade commented on src/Subsystems/Lights.cpp
> +  shooter = RobotMap::lightsShooter;
Use of member initializer list would be more consistant

2017-01-02 01:51 UTC, Diego-Andrade commented on src/Subsystems/Lights.cpp
> +  //SetDefaultCommand(new MySpecialCommand());
No default command?

2017-01-09 05:46 UTC, duane701 commented on src/Subsystems/Lights.cpp
> +  //SetDefaultCommand(new MySpecialCommand());
This is correct. The lights do not have a default command. Lights are turned on and off only explicitly. There is no command that needs to continue running.

In the future, perhaps, lights would be controlled by a command.

2017-01-09 05:51 UTC, duane701 commented
PTAL

I have added the changes as a fixup! I will create a new branch with the fixed changes in place.

However, in the mean time you can review these changes as they are.

2017-01-09 05:53 UTC, duane701 commented
Replaced by #17.

2017-01-09 05:53 UTC, closed without merging